dist: jammy
language: python
python:
  - "3.9"

install:
  - "pip install pipx"
  - "pipx install poetry"

# 定义不同的工作流程
jobs:
  include:
    # 主分支合并流程
    - name: "Master Branch"
      if: type = push AND branch = master
      script:
        - poetry install --no-root
        - poetry run make test

    # 合并请求检查流程
    - name: "Pull Request Checks"
      if: type = pull_request AND branch = master
      script:
        - poetry install
        - poetry run make lint test
