language: python

# 指定使用Docker服务
services:
  - docker

install:
  - 'echo nothing'

script:
  - 'echo nothing'

# 定义不同的工作流程
jobs:
  include:
    # 主分支合并流程
    - name: "Master Branch"
      if: branch = master
      script:
        - "docker build -t devbot ."
        # 在镜像中运行make test命令
        - docker run devbot make test

    # 合并请求检查流程
    - name: "Pull Request Checks"
      if: type = pull_request AND branch = master
      script:
        - "docker build -t devbot ."
        # 在镜像中运行make lint test命令
        - docker run devbot make lint test
