version: '3'

services:
  devbot:
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    command: bash startup_in_docker.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

  smee-client:
    image: deltaprojects/smee-client
    entrypoint: sh /app/start_smee.sh
    volumes:
      - ./start_smee.sh:/app/start_smee.sh:ro
    env_file:
      - .env
